"""first build

Revision ID: fbc60c3a19cd
Revises: 
Create Date: 2025-05-08 14:07:39.641539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'fbc60c3a19cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('ACCOMO',
    sa.Column('accomo_id', sa.String(length=36), nullable=False),
    sa.Column('a_name', sa.String(length=100), nullable=False, comment='店家名'),
    sa.Column('county', sa.String(length=3), nullable=True, comment='縣市'),
    sa.Column('address', sa.String(length=100), nullable=True, comment='地址'),
    sa.Column('rate', sa.DECIMAL(precision=2, scale=1), nullable=True, comment='評分'),
    sa.Column('geo_loc', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('pic_url', sa.Text(), nullable=True, comment='圖片URL'),
    sa.Column('b_url', sa.Text(), nullable=True, comment='BOOKING 連結'),
    sa.Column('ac_type', sa.String(length=3), nullable=True, comment='類型'),
    sa.Column('comm', sa.Integer(), nullable=True, comment='評論數'),
    sa.Column('area', sa.String(length=3), nullable=True, comment='鄉鎮區'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('NULL ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('accomo_id')
    )
    op.create_geospatial_index('idx_ACCOMO_geo_loc', 'ACCOMO', ['geo_loc'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_geo_loc', 'ACCOMO', ['geo_loc'], unique=False, mysql_prefix='SPATIAL', postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('ACTIVITY',
    sa.Column('events_id', sa.String(length=36), nullable=False),
    sa.Column('ev_name', sa.String(length=100), nullable=False, comment='活動名稱'),
    sa.Column('county', sa.String(length=3), nullable=True, comment='縣市'),
    sa.Column('address', sa.String(length=100), nullable=True, comment='地址'),
    sa.Column('geo_loc', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('pic_url', sa.Text(), nullable=True, comment='圖片URL'),
    sa.Column('accu_url', sa.Text(), nullable=True, comment='ACCUPASS 連結'),
    sa.Column('area', sa.String(length=3), nullable=True, comment='鄉鎮區'),
    sa.Column('s_time', sa.String(length=120), nullable=True, comment='開始時間'),
    sa.Column('e_time', sa.String(length=120), nullable=True, comment='結束時間'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('NULL ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('events_id')
    )
    op.create_geospatial_index('idx_ACTIVITY_geo_loc', 'ACTIVITY', ['geo_loc'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_geo_loc', 'ACTIVITY', ['geo_loc'], unique=False, mysql_prefix='SPATIAL', postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('EXHIBIT',
    sa.Column('exhibit_id', sa.String(length=36), nullable=False),
    sa.Column('ex_name', sa.String(length=100), nullable=False, comment='展演名稱'),
    sa.Column('county', sa.String(length=3), nullable=True, comment='縣市'),
    sa.Column('address', sa.String(length=100), nullable=True, comment='地址'),
    sa.Column('geo_loc', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('pic_url', sa.Text(), nullable=True, comment='圖片URL'),
    sa.Column('klook_url', sa.Text(), nullable=True, comment='KLOOK 連結'),
    sa.Column('area', sa.String(length=3), nullable=True, comment='鄉鎮區'),
    sa.Column('s_time', sa.DateTime(), nullable=True, comment='開始時間'),
    sa.Column('e_time', sa.String(length=120), nullable=True, comment='結束時間'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('NULL ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('exhibit_id')
    )
    op.create_geospatial_index('idx_EXHIBIT_geo_loc', 'EXHIBIT', ['geo_loc'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_geo_loc', 'EXHIBIT', ['geo_loc'], unique=False, mysql_prefix='SPATIAL', postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('FOOD',
    sa.Column('food_id', sa.String(length=36), nullable=False),
    sa.Column('f_name', sa.String(length=100), nullable=False, comment='店家名'),
    sa.Column('b_hours', sa.String(length=120), nullable=True, comment='營業時間'),
    sa.Column('county', sa.String(length=3), nullable=True, comment='縣市'),
    sa.Column('address', sa.String(length=100), nullable=True, comment='地址'),
    sa.Column('rate', sa.DECIMAL(precision=2, scale=1), nullable=True, comment='評分'),
    sa.Column('geo_loc', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('pic_url', sa.Text(), nullable=True, comment='圖片URL'),
    sa.Column('gmaps_url', sa.Text(), nullable=True, comment='GOOGLE MAPS連結'),
    sa.Column('f_type', sa.String(length=3), nullable=True, comment='類型'),
    sa.Column('comm', sa.Integer(), nullable=True, comment='評論數'),
    sa.Column('area', sa.String(length=3), nullable=True, comment='區域'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('NULL ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_geospatial_index('idx_FOOD_geo_loc', 'FOOD', ['geo_loc'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_geo_loc', 'FOOD', ['geo_loc'], unique=False, mysql_prefix='SPATIAL', postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('SPOT',
    sa.Column('spot_id', sa.String(length=36), nullable=False),
    sa.Column('s_name', sa.String(length=100), nullable=False, comment='景點名'),
    sa.Column('b_hours', sa.String(length=120), nullable=True, comment='營業時間'),
    sa.Column('county', sa.String(length=3), nullable=True, comment='縣市'),
    sa.Column('address', sa.String(length=100), nullable=True, comment='地址'),
    sa.Column('rate', sa.DECIMAL(precision=2, scale=1), nullable=True, comment='評分'),
    sa.Column('geo_loc', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('pic_url', sa.Text(), nullable=True, comment='圖片URL'),
    sa.Column('gmaps_url', sa.Text(), nullable=True, comment='GOOGLE MAPS連結'),
    sa.Column('s_type', sa.String(length=3), nullable=True, comment='類型'),
    sa.Column('comm', sa.Integer(), nullable=True, comment='評論數'),
    sa.Column('area', sa.String(length=3), nullable=True, comment='區域'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('NULL ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('spot_id')
    )
    op.create_geospatial_index('idx_SPOT_geo_loc', 'SPOT', ['geo_loc'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_geo_loc', 'SPOT', ['geo_loc'], unique=False, mysql_prefix='SPATIAL', postgresql_using='gist', postgresql_ops={})
    op.create_table('line_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=100), nullable=False, comment='Line UserId'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_geospatial_table('sample_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='名稱'),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_location', 'sample_location', ['location'], unique=False, mysql_prefix='SPATIAL', postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_sample_location_location', 'sample_location', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_sample_location_location', table_name='sample_location', postgresql_using='gist', column_name='location')
    op.drop_geospatial_index('idx_location', table_name='sample_location', mysql_prefix='SPATIAL', column_name='location')
    op.drop_geospatial_table('sample_location')
    op.drop_table('line_user')
    op.drop_geospatial_index('idx_geo_loc', table_name='SPOT', mysql_prefix='SPATIAL', column_name='geo_loc')
    op.drop_geospatial_index('idx_SPOT_geo_loc', table_name='SPOT', postgresql_using='gist', column_name='geo_loc')
    op.drop_geospatial_table('SPOT')
    op.drop_geospatial_index('idx_geo_loc', table_name='FOOD', mysql_prefix='SPATIAL', column_name='geo_loc')
    op.drop_geospatial_index('idx_FOOD_geo_loc', table_name='FOOD', postgresql_using='gist', column_name='geo_loc')
    op.drop_geospatial_table('FOOD')
    op.drop_geospatial_index('idx_geo_loc', table_name='EXHIBIT', mysql_prefix='SPATIAL', column_name='geo_loc')
    op.drop_geospatial_index('idx_EXHIBIT_geo_loc', table_name='EXHIBIT', postgresql_using='gist', column_name='geo_loc')
    op.drop_geospatial_table('EXHIBIT')
    op.drop_geospatial_index('idx_geo_loc', table_name='ACTIVITY', mysql_prefix='SPATIAL', column_name='geo_loc')
    op.drop_geospatial_index('idx_ACTIVITY_geo_loc', table_name='ACTIVITY', postgresql_using='gist', column_name='geo_loc')
    op.drop_geospatial_table('ACTIVITY')
    op.drop_geospatial_index('idx_geo_loc', table_name='ACCOMO', mysql_prefix='SPATIAL', column_name='geo_loc')
    op.drop_geospatial_index('idx_ACCOMO_geo_loc', table_name='ACCOMO', postgresql_using='gist', column_name='geo_loc')
    op.drop_geospatial_table('ACCOMO')
    # ### end Alembic commands ###
